# Generated by Django 5.2.7 on 2025-11-17 12:10

import teacher.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='notes_pdfs')),
            ],
            options={
                'verbose_name': 'Assigment',
                'verbose_name_plural': 'Assigments',
            },
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=teacher.utils.get_year, max_length=4, verbose_name='Year')),
                ('month', models.CharField(default=teacher.utils.get_month, max_length=20, verbose_name='Month')),
                ('date', models.CharField(default=teacher.utils.get_date, max_length=2, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(verbose_name='Grade/Class')),
                ('section', models.CharField(blank=True, max_length=30, null=True, verbose_name='Section')),
                ('faculty', models.CharField(default='N/A', max_length=30, verbose_name='Faculty')),
                ('class_image', models.ImageField(blank=True, upload_to='class_image/', verbose_name='class_image')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='project title')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to='', verbose_name='Project content')),
                ('description', models.CharField(default='N/A', verbose_name='description')),
                ('teacher_message', models.TextField(blank=True, null=True, verbose_name='message form teacher')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', verbose_name='Project Status')),
            ],
            options={
                'verbose_name': 'project',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Subject Name')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
