# Generated by Django 5.2.7 on 2025-11-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_class', '0001_initial'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='classs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_class.class'),
        ),
        migrations.AddField(
            model_name='project',
            name='classs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_class.class'),
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='student.student_info'),
        ),
        migrations.AddField(
            model_name='project',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_class.subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(to='data_class.subject', verbose_name='Subjects'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_class.subject'),
        ),
    ]
