# Generated by Django 5.2.7 on 2025-11-20 07:14

import teacher.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='day',
            field=models.CharField(default=teacher.utils.get_day, max_length=10),
        ),
    ]
