# Generated by Django 5.2.7 on 2025-11-21 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0003_attendence_day'),
        ('student', '0007_student_attendance_delete_student_attendence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendence',
            new_name='Attendance',
        ),
    ]
