# Generated by Django 5.2.7 on 2025-11-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0004_rename_attendence_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('year', 'month', 'date')},
        ),
    ]
