# Generated by Django 5.2.7 on 2025-11-25 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0042_faculty_alter_head_faculty_teacher_faculty'),
        ('data_class', '0005_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.faculty'),
        ),
    ]
