# Generated by Django 5.2.7 on 2025-12-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0006_alter_class_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.CharField(verbose_name='Grade'),
        ),
    ]
