# Generated by Django 5.2.5 on 2025-09-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0023_alter_year_month_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year_month',
            options={'verbose_name': 'Year', 'verbose_name_plural': 'years'},
        ),
    ]
