# Generated by Django 5.2.7 on 2025-11-17 12:10

import django.db.models.deletion
import student.code
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_class', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('first_name', models.CharField(default='N/A', max_length=20)),
                ('last_name', models.CharField(default='N/A', max_length=20)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(default='Teacher@gmail.com', max_length=254, verbose_name='Email Address')),
                ('experience', models.IntegerField(default=0)),
                ('teacher_code', models.CharField(default=student.code.generate_unique_code, max_length=10, unique=True, verbose_name='teacher_Code')),
                ('teacher_image', models.ImageField(blank=True, null=True, upload_to='teacher_image/')),
                ('refrence_code', models.CharField(default='n?A', verbose_name='refrence_code')),
                ('head_teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_teacher', to='data_class.class')),
                ('subject', models.ManyToManyField(to='data_class.subject')),
                ('teacher_class', models.ManyToManyField(related_name='class_teacher', to='data_class.class', verbose_name='teacher_assigned_class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher_Account',
                'verbose_name_plural': 'Teacher_Accounts',
            },
        ),
    ]
