# Generated by Django 5.2.7 on 2026-01-19 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0055_delete_members'),
        ('teacher', '0002_teacher_account_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.member_role'),
        ),
    ]
