# Generated by Django 5.2.7 on 2025-10-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_teacher_refrence_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher_Account', 'verbose_name_plural': 'Teacher_Accounts'},
        ),
    ]
