# Generated by Django 5.2.1 on 2025-06-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='school _name')),
            ],
            options={
                'verbose_name': 'title name {schol name }',
            },
        ),
    ]
