# Generated by Django 5.2.1 on 2025-06-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'title name {schol name }', 'verbose_name_plural': 'School name'},
        ),
    ]
