# Generated by Django 5.2.1 on 2025-06-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_event_galleryimage_news_alter_slider_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quick_acess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academics', models.ImageField(upload_to='academics/')),
                ('admission', models.ImageField(upload_to='admission/')),
            ],
            options={
                'verbose_name_plural': 'Quick_Acess_Image',
            },
        ),
    ]
