# Generated by Django 5.2.1 on 2025-06-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_quick_acess'),
    ]

    operations = [
        migrations.AddField(
            model_name='quick_acess',
            name='academics_description',
            field=models.CharField(default='N/a', max_length=255),
        ),
        migrations.AddField(
            model_name='quick_acess',
            name='admission_description',
            field=models.CharField(default='N/a', max_length=255),
        ),
    ]
