# Generated by Django 5.2.1 on 2025-06-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_quick_acess_academics_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quick_acess_academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academics', models.ImageField(upload_to='academics/')),
                ('academics_description', models.CharField(default='N/a', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Quick_Acess_Image',
            },
        ),
        migrations.CreateModel(
            name='Quick_acess_admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission', models.ImageField(upload_to='admission/')),
                ('admission_description', models.CharField(default='N/a', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Quick_Acess_Image',
            },
        ),
        migrations.DeleteModel(
            name='Quick_acess',
        ),
    ]
