# Generated by Django 5.2.1 on 2025-06-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_achievements_alter_quick_acess_academics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name_plural': 'Achivement'},
        ),
        migrations.AddField(
            model_name='achievements',
            name='Faculty',
            field=models.IntegerField(default=0, max_length=100, verbose_name='Number of Faculty`s'),
        ),
    ]
