# Generated by Django 5.2.1 on 2025-06-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_achievements_options_achievements_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Academics', 'Academics'), ('Events', 'Events'), ('Student Life', 'Student Life'), ('Sports', 'Sports'), ('Announcements', 'Announcements')], default='School News', max_length=100),
        ),
    ]
