# Generated by Django 5.2.1 on 2025-06-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_news_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='catogery',
            field=models.CharField(choices=[('Events', 'Events'), ('Activities', 'Activities'), ('Achievements', 'Achievements'), ('Sports', 'Sports'), ('Cultural', 'Cultural')], default='Activities'),
        ),
    ]
