# Generated by Django 5.2.1 on 2025-06-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='catogery',
            new_name='category',
        ),
    ]
