# Generated by Django 5.2.1 on 2025-06-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_rename_catogery_galleryimage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_low', models.ImageField(choices=[('Grades K-5', 'Grades K-5'), ('Grades 6-8', 'Grades 6-8'), ('Grades 9-12', 'Grades 9-12')], null=True, upload_to='grade/')),
                ('low_des', models.TextField(verbose_name='Short description ')),
                ('grade_mid', models.ImageField(choices=[('Grades K-5', 'Grades K-5'), ('Grades 6-8', 'Grades 6-8'), ('Grades 9-12', 'Grades 9-12')], null=True, upload_to='grade/')),
                ('mid_des', models.TextField(verbose_name='Short description ')),
                ('grade_high', models.ImageField(choices=[('Grades K-5', 'Grades K-5'), ('Grades 6-8', 'Grades 6-8'), ('Grades 9-12', 'Grades 9-12')], null=True, upload_to='grade/')),
                ('high_des', models.TextField(verbose_name='Short description ')),
            ],
            options={
                'verbose_name': 'Academics_Info',
                'verbose_name_plural': 'Academicss_Info',
            },
        ),
    ]
