# Generated by Django 5.2.1 on 2025-06-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_academics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='grade_high',
            field=models.ImageField(null=True, upload_to='grade/'),
        ),
        migrations.AlterField(
            model_name='academics',
            name='grade_low',
            field=models.ImageField(null=True, upload_to='grade/'),
        ),
        migrations.AlterField(
            model_name='academics',
            name='grade_mid',
            field=models.ImageField(null=True, upload_to='grade/'),
        ),
    ]
