# Generated by Django 5.2.1 on 2025-06-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_academics_grade_high_alter_academics_grade_low_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_image', models.ImageField(upload_to='faculty/')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_social_link', models.TextField(verbose_name='social link Like [ facebook , Gmail ] only one !')),
                ('teacher_faculty', models.CharField(max_length=50, verbose_name='teacher faculty name ')),
                ('teahcer_description', models.TextField(verbose_name='short info about the teacher')),
            ],
        ),
        migrations.AlterModelOptions(
            name='academics',
            options={'verbose_name': 'Academic Level', 'verbose_name_plural': 'Academic Levels'},
        ),
    ]
