# Generated by Django 5.2.1 on 2025-06-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_head_faculty_alter_academics_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='head_faculty',
            options={'managed': True, 'verbose_name': 'Faculty_teacher_info', 'verbose_name_plural': 'Faculty_teacher_infos'},
        ),
        migrations.RenameField(
            model_name='head_faculty',
            old_name='teahcer_description',
            new_name='teacher_description',
        ),
        migrations.AlterModelTable(
            name='head_faculty',
            table='',
        ),
    ]
