# Generated by Django 5.2.1 on 2025-06-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_academic_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(verbose_name='applicant_Name ')),
                ('email', models.EmailField(max_length=254, verbose_name='applicant_Email')),
                ('contact', models.IntegerField(max_length=10, verbose_name='applicant_contact')),
                ('faculty', models.TextField(verbose_name='applicant_choosen_faculty')),
                ('message', models.TextField(verbose_name='applicant_message')),
            ],
            options={
                'verbose_name': 'Applications',
            },
        ),
        migrations.AlterModelOptions(
            name='academic_resources',
            options={'managed': True, 'verbose_name': 'Academic_resource', 'verbose_name_plural': 'Academic_resources'},
        ),
        migrations.AlterModelTable(
            name='academic_resources',
            table='',
        ),
    ]
