# Generated by Django 5.2.1 on 2025-06-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_contact_alter_academic_resources_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Applicant'},
        ),
    ]
