# Generated by Django 5.2.1 on 2025-06-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='head_faculty',
            table=None,
        ),
    ]
