# Generated by Django 5.2.1 on 2025-06-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_alter_head_faculty_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('Events', 'Events'), ('Activities', 'Activities'), ('Achievements', 'Achievements'), ('Sports', 'Sports'), ('Cultural', 'Cultural'), ('Notice', 'Notice')], default='Activities'),
        ),
    ]
