# Generated by Django 5.2.5 on 2025-09-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0040_alter_news_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name': 'Achivement', 'verbose_name_plural': 'Achivements'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Applicant', 'verbose_name_plural': 'Applicants'},
        ),
    ]
