# Generated by Django 5.2.7 on 2025-11-25 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0041_alter_achievements_options_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Faculty_info',
                'verbose_name_plural': 'Faculty_infos',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='head_faculty',
            name='teacher_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.faculty'),
        ),
    ]
