# Generated by Django 5.2.7 on 2025-11-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0042_faculty_alter_head_faculty_teacher_faculty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Head_faculty',
            new_name='Faculty_Teacher_Info',
        ),
    ]
