# Generated by Django 5.2.7 on 2025-11-25 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0043_rename_head_faculty_faculty_teacher_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'managed': True, 'verbose_name': 'Add_Faculty', 'verbose_name_plural': 'Add_Faculties'},
        ),
        migrations.AddField(
            model_name='members',
            name='member_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.member_role'),
        ),
    ]
