# Generated by Django 5.2.7 on 2025-11-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0044_member_role_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievements',
            new_name='Achievements_stats',
        ),
        migrations.AlterModelOptions(
            name='achievements_stats',
            options={'verbose_name': 'Achivement stats', 'verbose_name_plural': 'Achivement stats'},
        ),
        migrations.AlterModelOptions(
            name='member_role',
            options={'verbose_name': 'Member_Role', 'verbose_name_plural': 'Member_Roles'},
        ),
    ]
