# Generated by Django 5.2.7 on 2025-11-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0045_rename_achievements_achievements_stats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic_resources',
            old_name='Academic_Policies',
            new_name='Admission_guide',
        ),
        migrations.RemoveField(
            model_name='academic_resources',
            name='Course_Catalogs',
        ),
        migrations.RemoveField(
            model_name='academic_resources',
            name='Study_Guides',
        ),
        migrations.AlterField(
            model_name='academics',
            name='grade_high',
            field=models.ImageField(null=True, upload_to='grade/', verbose_name='high grade'),
        ),
        migrations.AlterField(
            model_name='academics',
            name='grade_low',
            field=models.ImageField(null=True, upload_to='grade/', verbose_name='lower grade'),
        ),
        migrations.AlterField(
            model_name='academics',
            name='grade_mid',
            field=models.ImageField(null=True, upload_to='grade/', verbose_name='middle grade'),
        ),
    ]
