# Generated by Django 5.2.7 on 2025-11-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0046_rename_academic_policies_academic_resources_admission_guide_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic_resources',
            old_name='Academic_Calendar',
            new_name='academic_calendar',
        ),
        migrations.RenameField(
            model_name='academic_resources',
            old_name='Admission_guide',
            new_name='admission_guide',
        ),
    ]
