# Generated by Django 5.2.7 on 2025-11-26 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0047_rename_academic_calendar_academic_resources_academic_calendar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('review', models.TextField(verbose_name='review')),
                ('image', models.ImageField(upload_to='review/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_of', models.IntegerField(verbose_name='class_of')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.faculty', verbose_name='faculty')),
            ],
            options={
                'verbose_name': 'Student_Review',
                'verbose_name_plural': 'Student_Reviews',
            },
        ),
    ]
