# Generated by Django 5.2.7 on 2025-12-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0048_student_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Principal Name')),
                ('image', models.ImageField(upload_to='principal/')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'principal',
                'verbose_name_plural': 'Principal',
            },
        ),
    ]
