# Generated by Django 5.2.7 on 2025-12-02 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0049_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Achivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='academic_achivements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sports_Achivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='sports_achivements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Achivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_achivements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.academic_achivements')),
                ('sports_achivements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.sports_achivements')),
            ],
            options={
                'verbose_name': 'Achivement',
                'verbose_name_plural': 'Achivements',
            },
        ),
    ]
