# Generated by Django 5.2.7 on 2025-12-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0050_academic_achivements_sports_achivements_achivements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Time_Line',
                'verbose_name_plural': 'Time_Lines',
            },
        ),
        migrations.AlterModelOptions(
            name='academic_achivements',
            options={'verbose_name': 'Academic Achivement', 'verbose_name_plural': 'Academic Achivements'},
        ),
        migrations.AlterModelOptions(
            name='sports_achivements',
            options={'verbose_name': 'Sports Achivement', 'verbose_name_plural': 'Sports Achivements'},
        ),
    ]
