# Generated by Django 5.2.7 on 2025-12-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0051_time_line_alter_academic_achivements_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achivements',
        ),
    ]
