# Generated by Django 5.2.7 on 2025-12-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0053_important_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='faculty',
        ),
        migrations.AddField(
            model_name='contact',
            name='matter_of_subject',
            field=models.TextField(default='', verbose_name='applicant_matter_of_subject'),
        ),
    ]
