# Generated by Django 5.2.7 on 2026-01-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0054_remove_contact_faculty_contact_matter_of_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
