# Generated by Django 5.2.7 on 2025-11-17 12:10

import django.db.models.deletion
import student.code
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_class', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('student_code', models.CharField(default=student.code.generate_unique_code, max_length=10, unique=True, verbose_name='Student Code')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_profile', models.ImageField(blank=True, upload_to='student/')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='student_age')),
                ('email', models.EmailField(max_length=254, verbose_name='student_email')),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], null=True, verbose_name='Gender')),
                ('Roll_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='student_roll number')),
                ('refrence_code', models.CharField(default='n?A', verbose_name='refrence_code')),
                ('joined', models.BooleanField(blank=True, default=False, null=True)),
                ('father_name', models.CharField(blank=True, null=True, verbose_name='father_name')),
                ('mother_name', models.CharField(blank=True, null=True, verbose_name='mother_name')),
                ('parent_contact', models.IntegerField(blank=True, null=True, verbose_name='contact')),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='parent_email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('emergency_contact', models.IntegerField(blank=True, null=True, verbose_name='emergency conmtact')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_class.class', verbose_name='student_class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Associated_Student')),
            ],
            options={
                'verbose_name': 'Student_Account',
                'verbose_name_plural': 'Student_Accounts',
            },
        ),
        migrations.CreateModel(
            name='Student_Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attented', models.BooleanField(default=False)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_class.attendence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_info')),
            ],
        ),
    ]
