# Generated by Django 5.2.7 on 2025-11-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_attendence',
            old_name='attented',
            new_name='attended',
        ),
    ]
