# Generated by Django 5.2.7 on 2025-11-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_attented_student_attendence_attended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_attendence',
            old_name='year',
            new_name='attendence',
        ),
    ]
