# Generated by Django 5.2.7 on 2025-11-20 07:12

import teacher.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_year_student_attendence_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_attendence',
            name='day',
            field=models.CharField(default=teacher.utils.get_day, max_length=10),
        ),
    ]
