# Generated by Django 5.2.7 on 2025-11-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_attendence_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_attendence',
            name='day',
        ),
    ]
