# Generated by Django 5.2.7 on 2025-11-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0003_attendence_day'),
        ('student', '0005_remove_student_attendence_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_attendence',
            unique_together={('student', 'attendence')},
        ),
    ]
