# Generated by Django 5.2.7 on 2025-11-21 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0003_attendence_day'),
        ('student', '0006_alter_student_attendence_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_class.attendence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_info')),
            ],
            options={
                'unique_together': {('student', 'attendance')},
            },
        ),
        migrations.DeleteModel(
            name='Student_Attendence',
        ),
    ]
