# Generated by Django 5.2.7 on 2026-01-10 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_attendance_delete_student_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='account_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
