# Generated by Django 5.2.7 on 2026-01-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_info_account_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_info',
            old_name='emergency_contact',
            new_name='student_contact',
        ),
    ]
