# Generated by Django 5.2.7 on 2026-01-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_rename_emergency_contact_student_info_student_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='student_contact',
            field=models.IntegerField(blank=True, null=True, verbose_name='student contact'),
        ),
    ]
