# Generated by Django 5.2.5 on 2025-08-31 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_alter_attendence_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
