# Generated by Django 5.2.5 on 2025-08-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_alter_student_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
