# Generated by Django 5.2.5 on 2025-09-13 14:34

import django.db.models.deletion
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0024_alter_year_month_options'),
        ('student', '0032_alter_student_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='attendence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_class.year_month', verbose_name='Month/Year'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='date_month',
            field=models.DateField(blank=True, default=student.models.get_today_date, verbose_name='Month/Date'),
        ),
    ]
