# Generated by Django 5.2.7 on 2025-10-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_alter_attendence_attendence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendence',
            options={'verbose_name': 'Student_Attendence'},
        ),
        migrations.AlterModelOptions(
            name='student_info',
            options={'verbose_name': 'Student_Account', 'verbose_name_plural': 'Student_Accounts'},
        ),
    ]
